"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from .ats_applicants import AtsApplicants
from .ats_applications import AtsApplications
from .ats_jobs import AtsJobs
from .sdkconfiguration import SDKConfiguration

class Ats:
    applicants: AtsApplicants
    applications: AtsApplications
    jobs: AtsJobs
    sdk_configuration: SDKConfiguration

    def __init__(self, sdk_config: SDKConfiguration) -> None:
        self.sdk_configuration = sdk_config
        self._init_sdks()
    
    def _init_sdks(self):
        self.applicants = AtsApplicants(self.sdk_configuration)
        self.applications = AtsApplications(self.sdk_configuration)
        self.jobs = AtsJobs(self.sdk_configuration)
        
    