"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from apideck import utils
from dataclasses_json import Undefined, dataclass_json
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class MetaCursors:
    r"""Cursors to navigate to previous or next pages through the API"""
    current: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('current') }})
    r"""Cursor to navigate to the current page of results through the API"""
    next: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('next') }})
    r"""Cursor to navigate to the next page of results through the API"""
    previous: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('previous') }})
    r"""Cursor to navigate to the previous page of results through the API"""
    



@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class Meta:
    r"""Response metadata"""
    cursors: Optional[MetaCursors] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('cursors'), 'exclude': lambda f: f is None }})
    r"""Cursors to navigate to previous or next pages through the API"""
    items_on_page: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('items_on_page'), 'exclude': lambda f: f is None }})
    r"""Number of items returned in the data property of the response"""
    

