"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from apideck import utils
from dataclasses_json import Undefined, dataclass_json
from typing import Any, Dict, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class PassThroughQuery:
    additional_properties: Optional[Dict[str, Any]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'exclude': lambda f: f is None }})
    example_downstream_property: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'example_downstream_property' }})
    r"""All passthrough query parameters are passed along to the connector as is (?pass_through[search]=leads becomes ?search=leads)"""
    

