"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from apideck import utils
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from typing import Optional

class PhoneNumberType(str, Enum):
    r"""The type of phone number"""
    PRIMARY = 'primary'
    SECONDARY = 'secondary'
    HOME = 'home'
    WORK = 'work'
    OFFICE = 'office'
    MOBILE = 'mobile'
    ASSISTANT = 'assistant'
    FAX = 'fax'
    DIRECT_DIAL_IN = 'direct-dial-in'
    PERSONAL = 'personal'
    OTHER = 'other'


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class PhoneNumber:
    number: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('number') }})
    r"""The phone number"""
    area_code: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('area_code') }})
    r"""The area code of the phone number, e.g. 323"""
    country_code: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('country_code') }})
    r"""The country code of the phone number, e.g. +1"""
    extension: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('extension') }})
    r"""The extension of the phone number"""
    id: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('id') }})
    r"""Unique identifier of the phone number"""
    type: Optional[PhoneNumberType] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('type') }})
    r"""The type of phone number"""
    

