"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class JobStatus(str, Enum):
    r"""The status of the job."""
    DRAFT = 'draft'
    INTERNAL = 'internal'
    PUBLISHED = 'published'
    COMPLETED = 'completed'
    ON_HOLD = 'on-hold'
    PRIVATE = 'private'
